#to install the package, first git clone the repository, cd into the directory then type "R CMD INSTALL optDesignSlopeInt".

library(optDesignSlopeInt)
data(napth)
X = napth; rm(napth)

##### Section 3.1

# Fig 1a
par(mar = c(4.5,4,0.5,0.5))
plot(X$Vg_Vl, X$InvGC, xlab = "Gas-to-Liquid Ratio", ylab = "Inverse GC Area", main = "", cex = 1, pch = 1)
abline(v = 0.342, col = "red", lty = 3)
abline(v = 15, col = "red", lty = 3)

#we now "cut" our data
X = X[X$Vg_Vl >= 0.342 & X$Vg_Vl <= 15, ]

# Fig 1b
par(mar = c(4.5,2.5,0.5,0.5))
plot(X$Vg_Vl, X$InvGC, xlab = "Gas-to-Liquid Ratio", ylab = "", main = "", cex = 1, pch = 1)


##### Section 3.2

xmin = 5 / 15
xmax = 19 / 1
n = 10
theta0 = 0.053
opt_homo_design = oed_for_slope_over_intercept(n, xmin, xmax, theta0)
table(opt_homo_design)

##### Section 3.3

##Fig 1

#trial run data
mod = lm(X[,2] ~ X[,1])
summary(mod)

Nsim_figs = 50000
designs = rbind(
		seq(xmin, xmax, length.out = n),
		oed_for_slope_over_intercept(n, xmin, xmax, theta0)
)
gen_resp = function(xs, beta0 = 3.923e-09, sigma = 3.151e-10){
	beta0 + beta0 * theta0 * xs + rnorm(length(xs), 0, sigma)
}

#Fig 2
res = design_bakeoff(xmin, xmax, designs, draw_theta_at = theta0,
		gen_resp = gen_resp, Nsim = Nsim_figs, xlab_names = c("Evenly Spaced", "Optimal"))

#to get the rmse (similar to standard error)
intercentile_perf = lapply(res$ests, function(ests){quantile(ests, 0.99) - quantile(ests, 0.01)})
(intercentile_perf[[1]] - intercentile_perf[[2]]) / intercentile_perf[[2]]
rmse_perf = lapply(res$ests, function(ests){sqrt(sum((ests - theta0)^2) / Nsim_figs)})
(rmse_perf[[1]] - rmse_perf[[2]]) / rmse_perf[[2]]
vars = lapply(res$ests, function(ests){var(ests)})
vars[[1]] / vars[[2]]


##### Section 3.4

##Fig 3
fig2_res = err_vs_theta0_plot_for_homo_design(n, xmin, xmax, 
				theta = 0.053, theta0_min = 0.005, theta0_max = 1, beta0 = 3.923e-09, sigma =  3.151e-10,
				theta0 = theta0, Nsim = Nsim_figs, plot_rhos = TRUE)





##Table 2

gen_resp = function(xs, beta0 = 3.923e-09){
	beta0 + beta0 * theta0 * xs + rnorm(length(xs), 0, 3.151e-10)
}

#example interval
experimental_results(opt_homo_design, gen_resp(opt_homo_design))

#evaluate coverage probs
Nsim = 1000
cis_cover = matrix(NA, nrow = 6, ncol = Nsim)
for (i in 1 : Nsim){
	ys = gen_resp(opt_homo_design)
	cis = experimental_results(opt_homo_design, ys)$cis
	cis_cover[, i] = apply(cis, 1, function(ci){ci[1] <= theta0 && ci[2] >= theta0})
	cat(".")
}
rowSums(cis_cover == TRUE, na.rm = TRUE) / Nsim


#discussion
sum(res$ests[[3]] < 0)


#Section 4
gen_resp = function(xs, beta0 = 3.923e-09, sigma = 5 * 3.151e-10){
	beta0 + beta0 * theta0 * xs + rnorm(length(xs), 0, sigma)
}

previous_paper_study_reps = c(3,3,3,2,2,3,3,1,3,1)
previous_paper_designs = list(
	c(80.9, 161.8, 242.8, 323.7),
	c(39 ,199, 499, 999),
	c(1.01, 3.03, 9.08),
	c(4.6, 6.5, 10.2, 21.4),
	c(10.2, 21.3, 43.6, 73.3, 222),
	c(10.2, 43.8, 111, 447),
	c(4.5, 6.3, 10, 21 ),
	c(39 ,199, 499, 999 ),
	c(1.5, 2, 2.5, 3, 4, 5, 7, 10),
	c(4.6, 6.4, 10.2, 21.3)
)
previous_paper_theta0s = rep(1, length(previous_paper_study_reps))
Nsim_figs = 10000

eff_results = array(NA, length(previous_paper_study_reps))


for (i in 1 : length(previous_paper_study_reps)){
	r = previous_paper_study_reps[i]
	des =  previous_paper_designs[[i]]
	n = length(des) * r
	
	xmin = min(des)
	xmax = max(des)
	theta0 = previous_paper_theta0s[i]	
	exp_des = rbind(rep(des, r), oed_for_slope_over_intercept(n, xmin, xmax, theta0))

	res = design_bakeoff(xmin, xmax, exp_des, 
		draw_theta_at = theta0,
		gen_resp = gen_resp, 
		Nsim = Nsim_figs)
	eff_est = (sd(res$ests[[1]]) -  sd(res$ests[[2]])) / sd(res$ests[[2]])
	eff_results[i] = eff_est
	cat("design #", i, "eff gain in std err", eff_est, "\n")
}

#Table 3 is generated by replacing the 1 * sigma in line 97 with 0.5 * sigma and 2 * sigma 
t(t(round(eff_results * 100)))
#in the text
mean(eff_results * 100)

